on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  k6_transpile_bundle_test:
    name: Transpile, bundle and run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          yarn --frozen-lockfile

#       - name: Transpile and bundle test script
#         run: |
#           yarn webpack
          
      - name: Run k6 cloud test
        uses: k6io/action@v0.1
        with:
          filename: dist/cred-schema-ms-get-test.js
          cloud: true
          token: ${{ secrets.K6_CLOUD_API_TOKEN }}
